# -*- coding: utf-8 -*-
"""db_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxQItc0AXvjib60OrSi4TvadCw9bwhXu
"""

import pymysql
#일별 매출액
def get_monthly_data(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT DATE_FORMAT(sdate, '%m') AS `month`, 
            SUM(revenue) AS revenue, SUM(profit) AS profit
            FROM sales_book
            GROUP BY `month`
            ORDER BY `month`;
    """
    cur.execute(sql)
    results = cur.fetchall()

def set_month(config, params):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        update sales set sid=%s, sunit=%s where sid=%s;
    """
    cur.execute(sql, params)

    cur.close()
    conn.close()

def get_sales_company(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
   SELECT scompany, SUM(revenue) AS com_revenue, 
   SUM(profit) AS  com_profit
   FROM sales_book
   group BY scompany
   ORDER BY revenue desc;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

# 3. 거래처별 판매상품 및 수량
def get_products_by_company(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT scompany, pname, SUM(sunit) AS unit
            FROM sales_book
            GROUP BY scompany, pname
            ORDER BY scompany;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

# 4. 상품별 판매수량/매출/이익
def get_data_by_products(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT pname, SUM(sunit) AS unit,
		        SUM(revenue) AS revenue, SUM(profit) AS profit
            FROM sales_book
            GROUP BY pid
            ORDER BY pid;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results

# 5. 카테고리별 매출/이익
def get_data_by_category(config):
    conn = pymysql.connect(**config)
    cur = conn.cursor()

    sql = """
        SELECT pcategory, SUM(revenue) AS revenue, SUM(profit) AS profit
            FROM sales_book
            GROUP BY pcategory;
    """
    cur.execute(sql)
    results = cur.fetchall()

    cur.close()
    conn.close()
    return results